# Image de base : MySQL version 8.0
FROM mysql:8.0
# Variables d'environnement pour configurer MySQL
ENV MYSQL_DATABASE=blog_db
ENV MYSQL_USER=blog_user
ENV MYSQL_PASSWORD=password
ENV MYSQL_ROOT_PASSWORD=root_password
